# Generated by Django 5.1.2 on 2024-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ra',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='RA'),
        ),
    ]
